name: Deploy to OVH

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Deploy to OVH hosting
        uses: pitscher/ovh-deploy-hosting-action@v1
        env:
          OVH_HOSTING_USER: ${{ secrets.OVH_HOSTING_USER }}
          OVH_HOSTING_PASSWORD: ${{ secrets.OVH_HOSTING_PASSWORD }}
          OVH_HOSTING_DOMAIN: ssh.cluster006.hosting.ovh.net
          REPOSITORY_NAME: APIMazaire
          REPOSITORY_URL: https://github.com/BIGBen99/APIMazaire.git
